# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
#  push:
#    branches: [ "docker" ]
  pull_request:
    branches: [ "docker" ]
env:
  applicationfolder: spring-boot-hello-world-example
  AWS_REGION: ap-southeast-2
  S3BUCKET: slnews.info

permissions:
  contents: read

jobs:
  build:
    name: Build and package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11 and build
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: build
        #    - run: ./gradlew build --no-daemon
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
#      - name: Run bash script - WHERE AM I
#        #      run: ls -lrt build/libs
#        run: |
#          pwd
#          ls -lrt build/libs
#        shell: bash
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          image: vijithaepa/voting-backend
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/voting-backend:latest

#  upload:
#    needs: build
#    name: Upload to Docker
#    runs-on: ubuntu-latest
#    #    environment: Dev
#    steps:
#      - name: Run PWD
#        run: |
#          pwd
#          ls -lrt
#          echo 'ls -lrt build/libs'
#          ls -lrt build/libs
#        shell: bash
#      - name: Build and push
#        uses: docker/build-push-action@v4
#        with:
#          image: vijithaepa/voting-backend
#          context: ./
#          file: ./Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKERHUB_USERNAME }}/voting-backend:latest